version: "3.9"
services:
  app:
    build:
      context: .
    environment:
      - DJANGO_SUPERUSER_USERNAME
      - DJANGO_SUPERUSER_EMAIL
      - DJANGO_SUPERUSER_PASSWORD
      - ENVIRONMENT=docker
    restart: unless-stopped
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    container_name: dictate-app
  postgres:
    image: postgres:16-alpine3.18
    restart: unless-stopped
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - dictate-postgresql-1:/var/lib/postgresql/data
    container_name: dictate-postgres
  redis:
    image: redis:7.2-alpine3.18
    restart: unless-stopped
    container_name: dictate-redis
    volumes:
      - dictate-redis-1:/data
volumes:
  postgresql-dictate:
    driver: local
networks:
  default:
    name: dictate-default
  # backend
