version: "3.9"
services:
  app:
    build:
      context: .
    environment:
      - DJANGO_SUPERUSER_USERNAME
      - DJANGO_SUPERUSER_EMAIL
      - DJANGO_SUPERUSER_PASSWORD
      - ENVIRONMENT=docker
    restart: unless-stopped
    ports:
      - "8000:8000"
    depends_on:
      - postgres
  postgres:
    image: postgres:16-alpine3.18
    restart: unless-stopped
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - postgresql-data:/var/lib/postgresql/data
volumes:
  postgresql-data:
    driver: local
