# Generated by Django 4.2.7 on 2024-01-13 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_rename_users_meeting_participants"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notes",
            name="meeting",
            field=models.OneToOneField(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="api.meeting"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="recording",
            name="meeting",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recordings",
                to="api.meeting",
            ),
            preserve_default=False,
        ),
    ]
